### ISSUE TITLE
sgd archived in CRAN?

### ISSUE THREAD

**Issue by ikosmidis** [airoldilab/sgd#105]
Hi,

Perhaps you have noticed already but just in case it helps to mention that here, too: 

sgd appears to have been archived in CRAN
https://cran.r-project.org/web/packages/sgd/index.html.

Message is 
"Archived on 2018-01-23 as check problems were not corrected in time."

**Comment by ptoulis** [comment]
Thanks, Ioannis. We are trying to resolve this.

**Comment by lylejkim** [comment]
Hi Ioannis,
Thank you for the inquiry. It is now reinstated on CRAN.
