### ISSUE TITLE
Output Compatibility

### ISSUE THREAD

**Issue by lantian2012** [airoldilab/sgd#13]
I find that most regression results are compatible with summary(). For lm and glm, the summary includes the standard error and p-value of all estimated coefficients.
I think it would be hard to get the standard error for our package. Do you think we should exclude it from our package?

**Comment by dustinvtran** [comment]
See closing comment in https://github.com/airoldilab/sgd/issues/42. It's an open question whether we want sgd output to be compatible with `summary()` depending on the model, or whether sgd output to be the same across all models. I'm personally a fan of the second as it makes it easier for us to build generic routines which do things for arbitrary `sgd` objects.
