### ISSUE TITLE
Family for different link function

### ISSUE THREAD

**Issue by k-ye** [airoldilab/sgd#14]
I was working on supporting a certain family for all its valid link functions. I have put the theoretical derivation in `reference/glm_family_conclusion.pdf` and `reference/Distribution_LinkFunc_Relationship.pdf`. Basically, what we did in class was the canonical link function. And a bit more change is needed in score function \nabla log-likelihood if we are using some other link functions.

The practical issue I've encountered is that: at the first few iterations, the estimation of theta is very unstable, therefore it may easily produce some crazy value when calculating the score function. Is there any way to avoid this issue?

**Comment by dustinvtran** [comment]
Not necessary unless there are certain numerical reasons for using non-canonical forms.
