### ISSUE TITLE
P-dim Learning Rate Decreasing Too Fast

### ISSUE THREAD

**Issue by k-ye** [airoldilab/sgd#15]
Hi,

@lantian2012 and I was doing some experiments on Poisson model dataset. We found out that if using `p-dim` learning rate, the learning rate will drop too fast. This is mainly because `Idiag` matrix is the summation of the square of `score_function` in each iteration. And this value will soon goes up to around 1e+18 (when X are around 10, theta.true is around [0.5, 1], Y ~ Pois(exp(theta' X))), which means its inversion being as tiny as 1e-18. At this point, the learning rate is almost 0, which means in each update, theta will only change for really a small value.

@ptoulis Yesterday you said that we are calculating the square of the score function Gi^2 because this will approximate to the real Fisher Information Matrix. However, in our pset 3, it is listed that:
` I(\theta) = E(h'(x_n'theta) * x_n x_n') / phi`

It was using the expectation of the first derivative of transfer function (instead of the square of the score function). 

I've been trying to use something like `h'(x_n'theta)*(x_n x_n')` as learning rate. The result, though, was still disappointing.

**Comment by dustinvtran** [comment]
I spotted the error. The learning rate should not take into account any approximations to the Fisher information based on previous iterations. Each diagonal of the observed Fisher information is an approximation to `I(theta_n)` for different `n`. Hence it does not make sense to sum them up.
Therefore
```
Idiag = Idiag + diag(Gi * Gi.transpose())
```
should simply be 
```
Idiag = diag(Gi * Gi.transpose())
```

**Comment by ptoulis** [comment]
with that kind of MSE there can be no arguing :+1:

**Comment by dustinvtran** [comment]
On checking all the learning rates, I noticed `one-dim-eigen` is broken for some reason. I'll make another issue for it. Also, AdaGrad still does better than this learning rate for the very small number of experiments I ran on linear regression (the only difference is the square root). Will add another issue to discuss this because it needs more analysis.
