### ISSUE TITLE
Output of sgd

### ISSUE THREAD

**Issue by dustinvtran** [airoldilab/sgd#42]
It should collect as few large objects as possible, such as not `fitted.values` but of course keep `coefficients`. The storage of the parameter estimates is already quite large in our setting where we assume large number of observations and features.

**Comment by lantian2012** [comment]
fitted.values was added for glm compatibility. I think we need to look at what values are actually used by functions that take in the glm object.

**Comment by dustinvtran** [comment]
I think glm compatibility is a low priority compared to the additional time/space complexity of preserving it.

IMO we can add a flag to turn on GLM compatibility but by default it should be turned off. This is similar to how all the bigmemory-ish packages break compatibility with built-in functions and require their own tools such as `bigglm()`.

**Comment by ptoulis** [comment]
why is fitted.values very large?

**Comment by dustinvtran** [comment]
By large I mean `residuals`, `fitted.values`, `linear.predictors`, and `weights` are vectors of of size `N`, the total # of observations. I'm not sure if it makes sense to store them by default

**Comment by ptoulis** [comment]
no we shouldn't. But we could also allocate some constant space 
and store values periodically (e.g., every 100 iterations) depending 
on how much space, and %logging we wish to make.

Users could then define the %logging level.

**Comment by dustinvtran** [comment]
Output of sgd is now compatible for all models, since 2571a4c1f3b377cf186395c5e81beaa3c0fd9daa removed compatibility for the glm class. I removed it because not all things were working and it was tough maintaining what did work. We can discuss at some other time whether or not it makes sense to remove a unifying output of SGD, and to have separate types of output per model, e.g., SGD on GLM models to have GLM-compatible output.
