### ISSUE TITLE
Safe check for glm family fails

### ISSUE THREAD

**Issue by lantian2012** [airoldilab/sgd#47]
`sgd.theta <- sgd(y ~ ., data=dat, model="glm", model.control=list(family=poisson))`

gives error 
```
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "NULL"
```

`sgd.theta <- sgd(y ~ ., data=dat, model="glm", model.control=list(family=poisson()))` is working.

Both inputs should be supported.

**Comment by dustinvtran** [comment]
Oops, that's my fault when renaming the `family` argument in `valid_model_control`
