### ISSUE TITLE
Change Convergence Criterion

### ISSUE THREAD

**Issue by lantian2012** [airoldilab/sgd#54]
In current implementation, sgd stops at 1 pass of the dataset. We can do multiple passes, and stop the sgd when a convergence criterion is met.

**Comment by dustinvtran** [comment]
Setting this to high priority as this is crucial for timing benchmarks. That is, if we converge earlier than a full pass, then we should stop.

**Comment by dustinvtran** [comment]
This was added some time before ad886192b0dc65ef85b8fcd83c6ff5e2369138c2.
