### ISSUE TITLE
sgd package should be at the root directory of the repository

### ISSUE THREAD

**Issue by dustinvtran** [airoldilab/sgd#64]
```
devtools::install_github("airoldilab/sgd")
```
doesn't work anymore since the sgd package needs to be at the root of the repo, not in a subdirectory. I think in general for convention purposes, the package should be at the root of the repository anyways. We can make note of particular directories/files to delete or something whenever submitting to CRAN (we already do so for things like .gitignore).

**Comment by lantian2012** [comment]
Yep. That sounds good. Having the package in a subdirectory is a python convention. I think we can move `script` into `sgd`.
