### ISSUE TITLE
add color to run_exp plots and change x-axis to label based on number of passes

### ISSUE THREAD

**Issue by dustinvtran** [airoldilab/sgd#66]
```{R}
source("script/load_mnist.R")
source("script/multilogit.R")
source("script/plot.R")

library(sgd)
library(bigmemory)

dat <- load_mnist()
X <- dat$train$x
y <- dat$train$y
X_test <- dat$test$x
y_test <- dat$test$y

methods <- list("sgd", "ai-sgd", "implicit")
lrs <- list("adagrad", "one-dim", "one-dim")
np <- list(3, 3, 3)
names <- methods

run_exp(methods, names, lrs, np, X, y, X_test, y_test)
```
![screen shot 2015-05-29 at 7 17 55 pm](https://cloud.githubusercontent.com/assets/2569867/7894428/6f1d7a52-0637-11e5-8c34-be08b9315abf.png)

**Comment by lantian2012** [comment]
Do you think it makes sense that `ai-sgd` has worse error? Or is it caused by small training set size?

**Comment by dustinvtran** [comment]
Both yes. I believe in practice the standard recommendation is to start averaging after a single pass (what [Bottou](http://leon.bottou.org/projects/sgd) does).

**Comment by dustinvtran** [comment]
![screen shot 2015-05-30 at 4 25 22 pm](https://cloud.githubusercontent.com/assets/2569867/7899207/fe677030-06e8-11e5-80ca-6499e4c1ba19.png)
it's looking quite nice :)

**Comment by dustinvtran** [comment]
Added npasses in 6dbd981b8b6b60dea2fbd698b28e66011500fb34
