### ISSUE TITLE
Learning rate for categorical variables

### ISSUE THREAD

**Issue by lantian2012** [airoldilab/sgd#7]
Our current method of determining learning rate includes calculating the eigenvalues of X. For categorical variables, we now split categorical variables into several indicator variables, and put the indicator variables as columns into X. Should we exclude categorical variables when we calculate the covariance matrix and eigenvalues? (It takes effort!)

**Comment by dustinvtran** [comment]
Since we abandoned eigenvalue-based learning rates, this is no longer a concern.
