### ISSUE TITLE
Write knitr entry for sgd package.

### ISSUE THREAD

**Issue by ptoulis** [airoldilab/sgd#81]

**Comment by MarcinKosinski** [comment]
+1. That's better solution than codes in the `demo` directory.
You can also think about submitting an article to [R Journal](http://journal.r-project.org/) when you finish your vignette

**Comment by dustinvtran** [comment]
We just submitted a paper to arXiv that should document some of this better. Will turn it into a vignette soon, so stay tuned!

**Comment by dustinvtran** [comment]
Vignette now included as of d8f9bad7b8142796967df80cdada93c9b584a404
