### ISSUE TITLE
CITATION for the package

### ISSUE THREAD

**Issue by MarcinKosinski** [airoldilab/sgd#83]
Is there so far any recommended way of citing this package?
Normally this info should be in the `inst/CITATION` directory.

**Comment by dustinvtran** [comment]
You can run `citation("sgd")`, which will give you the appropriate citation and bibtex entry:

```{R}
> citation("sgd")

To cite package ‘sgd’ in publications use:

  Dustin Tran, Tian Lian and Panos Toulis (). sgd: Stochastic Gradient
  Descent for Scalable Estimation. R package version 0.1.
  https://github.com/airoldilab/sgd

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {sgd: Stochastic Gradient Descent for Scalable Estimation},
    author = {Dustin Tran and Tian Lian and Panos Toulis},
    note = {R package version 0.1},
    url = {https://github.com/airoldilab/sgd},
  }
```
It works for all packages. :)

**Comment by MarcinKosinski** [comment]
Thanks. I couldn't run this because of the Windows issue installation :)

2015-09-06 18:44 GMT+02:00 Dustin Tran <notifications@github.com>:
