### ISSUE TITLE
Bad example on logistic regression

### ISSUE THREAD

**Issue by hxd1011** [airoldilab/sgd#95]
Following example in sgd function help document, The results will almost **always give probability close to 1.0**. May be we can have a better example in the help page. This example makes "logistic regression example" very strange.

	library(sgd)
	set.seed(42)
	data("winequality")
	dat <- winequality
	dat$quality <- as.numeric(dat$quality > 5) # transform to binary
	lg.sgd <- sgd(quality ~ ., data=dat,
					 model="glm", model.control=binomial(link="logit"),
					 sgd.control=list(reltol=1e-5, npasses=200),
					 lr.control=c(scale=1, gamma=1, alpha=30, c=1))

	p=predict(lg.sgd,as.matrix(dat))
	hist(p)

Note, this happens on other data set.

see [here](https://stats.stackexchange.com/questions/282684/what-cause-x-beta-shift-from-stochastic-gradient-descent-comparing-to-logistic)

**Comment by hxd1011** [comment]
I spent a lot of time on this problem, and found the "solution".

In fact the optimization algorithm works well, but logistic regression example is bad. Making `reltol=1e-10` in logistic regression example would be much better.

**Comment by dustinvtran** [comment]
Good catch. PR welcome to make this tweak.
