### ISSUE TITLE
sgd.function is empty

### ISSUE THREAD

**Issue by karldw** [airoldilab/sgd#99]
Is it supposed to be?

Here's the chunk of [source code](https://github.com/airoldilab/sgd/blob/89ab202e1163208b12e73738779ffc76169d14e4/R/sgd.R#L247):
```r

#' @export
#' @rdname sgd
sgd.function <- function(x, ...) {
}
#sgd.function <- function(x, gr=NULL, X, y,
#                         nparams,
#                         sgd.control=list(...),
#                         ...) {
#  model <- "gmm"
#  model.control <- list(model="gmm", fn=fn, gr=gr, d=ncol(X), nparams=nparams)
#  return(sgd.matrix(X, y, model, model.control, sgd.control))
#}

```

**Comment by dustinvtran** [comment]
Great question. I think we had thought of allowing a function as the first input, but eventually decided that this API wasn't very intuitive in the first place.  We should remove `sgd.function` altogether.
